import type { Palette } from "../core/types";
import { border, surface, textMuted } from "../core/ui";
import { PerPaletteGenerator } from "./base";

/**
 * fzf has no native theme file format. Colors are supplied via repeated
 * `--color=NAME:VALUE` options, usually collected in `FZF_DEFAULT_OPTS`.
 *
 * Each variant is emitted as a shell snippet that *appends* a Senzu color
 * spec to `FZF_DEFAULT_OPTS`, so it composes with layout/key-binding options
 * the user already sets. Source the file for the variant you want, e.g. in
 * zsh:
 *
 *   [ -f ~/.config/fzf/senzu.sh ] && . ~/.config/fzf/senzu.sh
 *
 * fzf merges multiple `--color` flags, and later entries win per element, so
 * sourcing a different variant file (or any other `--color` you append after)
 * overrides the Senzu values cleanly.
 */
export class FzfGenerator extends PerPaletteGenerator {
  name = "fzf";
  description = "fzf fuzzy finder (--color opts)";
  fileExtension = ".sh";

  generate(palette: Palette): string {
    const { ansi, semantic } = palette;
    const hl = ansi.yellow;
    const prompt = ansi.blue;
    const pointer = palette.cursor;
    const marker = ansi.green;
    const spinner = ansi.magenta;
    const info = semantic.info;
    const headerColor = textMuted(palette);
    const borderColor = border(palette);
    const bgPlus = palette.selection_background;
    const previewBg = surface(palette);

    const spec = [
      `fg:${palette.foreground}`,
      `bg:${palette.background}`,
      `hl:${hl}`,
      `fg+:${ansi.white}`,
      `bg+:${bgPlus}`,
      `hl+:${hl}`,
      `info:${info}`,
      `border:${borderColor}`,
      `prompt:${prompt}`,
      `pointer:${pointer}`,
      `marker:${marker}`,
      `spinner:${spinner}`,
      `header:${headerColor}`,
      `gutter:${bgPlus}`,
      `preview-fg:${palette.foreground}`,
      `preview-bg:${previewBg}`,
    ].join(",");

    return `#!/usr/bin/env sh
# Senzu Theme for fzf: ${palette.name}
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/${this.paletteKey(palette)}.sh ] && . ~/.config/fzf/${this.paletteKey(palette)}.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="\${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=${spec}"
`;
  }
}
