import type { Palette } from "../core/types";
import { elevatedSurface, textMuted } from "../core/ui";
import { PerPaletteGenerator } from "./base";

export interface HerdrThemeConfig {
  name: string;
  auto_switch: boolean;
  custom: Record<string, string>;
}

export function buildHerdrTheme(palette: Palette): HerdrThemeConfig {
  const baseTheme =
    palette.appearance === "light" ? "catppuccin-latte" : "catppuccin";
  const muted = palette.colors.scorpion ?? textMuted(palette);
  const overlay = palette.colors.grey ?? textMuted(palette);

  // Higher contrast means lighter text on dark palettes and darker text on
  // light palettes.
  const overlay0 = palette.appearance === "light" ? overlay : muted;
  const overlay1 = palette.appearance === "light" ? muted : overlay;

  return {
    name: baseTheme,
    auto_switch: false,
    custom: {
      accent: palette.ui["panel.focused_border"] ?? palette.cursor,
      panel_bg: palette.ui["panel.background"] ?? palette.background,
      surface0:
        palette.colors.grey_three ??
        palette.ui["element.background"] ??
        elevatedSurface(palette),
      surface1: palette.selection_background,
      surface_dim: elevatedSurface(palette),
      overlay0,
      overlay1,
      text: palette.foreground,
      subtext0: palette.colors.grey_chateau ?? textMuted(palette),
      mauve: palette.ansi.magenta,
      green: palette.ansi.green,
      yellow: palette.ansi.yellow,
      red: palette.ansi.red,
      blue: palette.ansi.blue,
      teal: palette.ansi.cyan,
      peach: palette.colors.raw_sienna ?? palette.semantic.warning,
    },
  };
}

export class HerdrGenerator extends PerPaletteGenerator {
  name = "herdr";
  description = "Herdr agent multiplexer config snippet";
  fileExtension = ".toml";

  generate(palette: Palette): string {
    const theme = buildHerdrTheme(palette);
    const customColors = Object.entries(theme.custom)
      .map(([name, color]) => `${name} = "${color}"`)
      .join("\n");

    return `# Senzu Theme for Herdr: ${palette.name}
# Generated by senzu
#
# Merge these tables into ~/.config/herdr/config.toml, replacing any existing
# [theme] and [theme.custom] tables, then run: herdr server reload-config
#
# Herdr uses one shared set of custom colors, so custom light and dark palettes
# cannot switch automatically. Copy one Senzu variant at a time.

[theme]
name = "${theme.name}"
auto_switch = ${theme.auto_switch}

[theme.custom]
${customColors}
`;
  }
}
