import type { Palette } from "../core/types";
import { border, elevatedSurface, textAccent } from "../core/ui";
import { PerPaletteGenerator } from "./base";

/** Lazygit theme overrides that can be merged with an existing config. */
export class LazygitGenerator extends PerPaletteGenerator {
  name = "lazygit";
  description = "Lazygit theme override";
  fileExtension = ".yml";

  generate(palette: Palette): string {
    const { ansi, semantic } = palette;
    const activeBorder = textAccent(palette);
    const inactiveBorder = border(palette);
    const inactiveSelection = elevatedSurface(palette);
    const unstaged = palette.ui.version_control_deleted ?? semantic.error;

    return `# Senzu Theme for Lazygit: ${palette.name}
# Generated by senzu

gui:
  theme:
    activeBorderColor: ["${activeBorder}", "bold"]
    inactiveBorderColor: ["${inactiveBorder}"]
    searchingActiveBorderColor: ["${ansi.yellow}", "bold"]
    optionsTextColor: ["${ansi.blue}"]
    selectedLineBgColor: ["${palette.selection_background}"]
    inactiveViewSelectedLineBgColor: ["${inactiveSelection}"]
    cherryPickedCommitFgColor: ["${palette.background}"]
    cherryPickedCommitBgColor: ["${ansi.magenta}"]
    markedBaseCommitFgColor: ["${palette.background}"]
    markedBaseCommitBgColor: ["${ansi.yellow}"]
    unstagedChangesColor: ["${unstaged}"]
    defaultFgColor: ["${palette.foreground}"]
`;
  }
}
