import type { Palette } from "../core/types";
import {
  activeLine,
  activeLineNumber,
  border,
  lineNumber,
  surface,
  tabBar,
  textAccent,
  textMuted,
} from "../core/ui";
import { PerPaletteGenerator } from "./base";

export class NeovimGenerator extends PerPaletteGenerator {
  name = "neovim";
  description = "Neovim colorscheme";
  fileExtension = ".lua";

  generate(palette: Palette): string {
    const { ansi, ansi_bright, syntax, semantic } = palette;
    const variantName = palette.name.toLowerCase().replace(/\s+/g, "_");
    const activeLineBg = activeLine(palette);
    const lineNumbers = lineNumber(palette);
    const activeLineNr = activeLineNumber(palette);
    const surfaceBg = surface(palette);
    const borderCol = border(palette);
    const textMutedCol = textMuted(palette);
    const textAccentCol = textAccent(palette);
    const tabBarCol = tabBar(palette);

    return `-- Senzu Theme: ${palette.name}
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = '${variantName}'

-- Terminal colors
vim.g.terminal_color_0 = '${ansi.black}'
vim.g.terminal_color_1 = '${ansi.red}'
vim.g.terminal_color_2 = '${ansi.green}'
vim.g.terminal_color_3 = '${ansi.yellow}'
vim.g.terminal_color_4 = '${ansi.blue}'
vim.g.terminal_color_5 = '${ansi.magenta}'
vim.g.terminal_color_6 = '${ansi.cyan}'
vim.g.terminal_color_7 = '${ansi.white}'
vim.g.terminal_color_8 = '${ansi_bright.black}'
vim.g.terminal_color_9 = '${ansi_bright.red}'
vim.g.terminal_color_10 = '${ansi_bright.green}'
vim.g.terminal_color_11 = '${ansi_bright.yellow}'
vim.g.terminal_color_12 = '${ansi_bright.blue}'
vim.g.terminal_color_13 = '${ansi_bright.magenta}'
vim.g.terminal_color_14 = '${ansi_bright.cyan}'
vim.g.terminal_color_15 = '${ansi_bright.white}'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '${palette.foreground}', bg = '${palette.background}' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '${palette.foreground}', bg = '${palette.background}' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '${palette.cursor_text}', bg = '${palette.cursor}' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '${activeLineBg}' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '${activeLineBg}' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '${lineNumbers}' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '${activeLineNr}', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '${palette.selection_background}' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '${palette.background}', bg = '${ansi.yellow}' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '${palette.background}', bg = '${ansi_bright.yellow}' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '${borderCol}' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '${palette.foreground}', bg = '${surfaceBg}' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '${textMutedCol}', bg = '${surfaceBg}' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '${palette.foreground}', bg = '${surfaceBg}' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '${palette.background}', bg = '${textAccentCol}' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '${syntax.comment}', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '${syntax.string}' })
vim.api.nvim_set_hl(0, 'Number', { fg = '${syntax.number}' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '${syntax.constant}' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '${syntax.keyword}' })
vim.api.nvim_set_hl(0, 'Function', { fg = '${syntax.function}' })
vim.api.nvim_set_hl(0, 'Type', { fg = '${syntax.type}' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '${syntax.operator}' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '${palette.foreground}' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '${syntax.keyword}' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '${syntax.preproc}' })
vim.api.nvim_set_hl(0, 'Special', { fg = '${syntax.attribute}' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '${syntax.tag}' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '${palette.foreground}', bg = '${surfaceBg}' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '${borderCol}', bg = '${surfaceBg}' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '${textMutedCol}', bg = '${tabBarCol}' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '${tabBarCol}' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '${palette.foreground}', bg = '${surfaceBg}', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '${semantic.ok}' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '${semantic.error}' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '${semantic.warning}' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '${semantic.error}' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '${semantic.warning}' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '${semantic.info}' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '${semantic.hint}' })
`;
  }
}
