import { opaque } from "../core/color";
import type { Palette } from "../core/types";
import {
  activeLine,
  activeLineNumber,
  border,
  lineNumber,
  surface,
  tabBar,
  textAccent,
  textMuted,
} from "../core/ui";
import { PerPaletteGenerator } from "./base";

export class NeovimGenerator extends PerPaletteGenerator {
  name = "neovim";
  description = "Neovim colorscheme";
  fileExtension = ".lua";

  generate(palette: Palette): string {
    const { ansi, ansi_bright, syntax, semantic } = palette;
    const variantName = palette.name.toLowerCase().replace(/\s+/g, "_");
    // The active-line slot may carry an alpha channel (`#rrggbbaa`, valid in
    // Zed). Neovim's `nvim_set_hl` rejects alpha hex with E5113, so composite
    // it onto the editor background to preserve the intended appearance.
    const activeLineBg = opaque(activeLine(palette), palette.background);
    const lineNumbers = lineNumber(palette);
    const activeLineNr = activeLineNumber(palette);
    const surfaceBg = surface(palette);
    const borderCol = border(palette);
    const textMutedCol = textMuted(palette);
    const textAccentCol = textAccent(palette);
    const tabBarCol = tabBar(palette);
    // biome-ignore lint/complexity/useLiteralKeys: TypeScript resolves `constructor` as Function
    const constructorColor = syntax["constructor"];

    return `-- Senzu Theme: ${palette.name}
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = '${variantName}'

-- Terminal colors
vim.g.terminal_color_0 = '${ansi.black}'
vim.g.terminal_color_1 = '${ansi.red}'
vim.g.terminal_color_2 = '${ansi.green}'
vim.g.terminal_color_3 = '${ansi.yellow}'
vim.g.terminal_color_4 = '${ansi.blue}'
vim.g.terminal_color_5 = '${ansi.magenta}'
vim.g.terminal_color_6 = '${ansi.cyan}'
vim.g.terminal_color_7 = '${ansi.white}'
vim.g.terminal_color_8 = '${ansi_bright.black}'
vim.g.terminal_color_9 = '${ansi_bright.red}'
vim.g.terminal_color_10 = '${ansi_bright.green}'
vim.g.terminal_color_11 = '${ansi_bright.yellow}'
vim.g.terminal_color_12 = '${ansi_bright.blue}'
vim.g.terminal_color_13 = '${ansi_bright.magenta}'
vim.g.terminal_color_14 = '${ansi_bright.cyan}'
vim.g.terminal_color_15 = '${ansi_bright.white}'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '${palette.foreground}', bg = '${palette.background}' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '${palette.foreground}', bg = '${palette.background}' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '${palette.cursor_text}', bg = '${palette.cursor}' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '${activeLineBg}' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '${activeLineBg}' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '${lineNumbers}' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '${activeLineNr}', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '${palette.selection_background}' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '${palette.background}', bg = '${ansi.yellow}' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '${palette.background}', bg = '${ansi_bright.yellow}' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '${borderCol}' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '${palette.foreground}', bg = '${surfaceBg}' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '${textMutedCol}', bg = '${surfaceBg}' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '${palette.foreground}', bg = '${surfaceBg}' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '${palette.background}', bg = '${textAccentCol}' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '${syntax.comment}', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '${syntax.string}' })
vim.api.nvim_set_hl(0, 'Number', { fg = '${syntax.number}' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '${syntax.constant}' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '${syntax.keyword}' })
vim.api.nvim_set_hl(0, 'Function', { fg = '${syntax.function}' })
vim.api.nvim_set_hl(0, 'Type', { fg = '${syntax.type}' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '${syntax.operator}' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '${palette.foreground}' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '${syntax.keyword}' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '${syntax.preproc}' })
vim.api.nvim_set_hl(0, 'Special', { fg = '${syntax.attribute}' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '${syntax.tag}' })

-- Treesitter highlights
${this.hl("@variable", syntax.variable)}
${this.hl("@variable.builtin", syntax.variable)}
${this.hl("@variable.parameter", syntax.variable)}
${this.hl("@variable.parameter.builtin", syntax.variable)}
${this.hl("@variable.member", syntax.property)}
${this.hl("@constant", syntax.constant)}
${this.hl("@constant.builtin", syntax.constant)}
${this.hl("@constant.macro", syntax.constant)}
${this.hl("@number", syntax.number)}
${this.hl("@number.float", syntax.number)}
${this.hl("@boolean", syntax.boolean)}
${this.hl("@character", syntax.string)}
${this.hl("@character.special", syntax["string.special"])}
${this.hl("@string", syntax.string)}
${this.hl("@string.documentation", syntax["comment.doc"])}
${this.hl("@string.regexp", syntax["string.regex"])}
${this.hl("@string.escape", syntax["string.escape"])}
${this.hl("@string.special", syntax["string.special"])}
${this.hl("@string.special.symbol", syntax["string.special.symbol"])}
${this.hl("@string.special.path", syntax["string.special"])}
${this.hl("@string.special.url", syntax.link_uri)}
${this.hl("@function", syntax.function)}
${this.hl("@function.builtin", syntax["function.builtin"])}
${this.hl("@function.call", syntax.function)}
${this.hl("@function.macro", syntax.function)}
${this.hl("@method", syntax.function)}
${this.hl("@method.call", syntax.function)}
${this.hl("@constructor", constructorColor)}
${this.hl("@parameter", syntax.variable)}
${this.hl("@keyword", syntax.keyword)}
${this.hl("@keyword.coroutine", syntax.keyword)}
${this.hl("@keyword.function", syntax.keyword)}
${this.hl("@keyword.operator", syntax.keyword)}
${this.hl("@keyword.import", syntax.keyword)}
${this.hl("@keyword.type", syntax.type)}
${this.hl("@keyword.modifier", syntax.keyword)}
${this.hl("@keyword.repeat", syntax.keyword)}
${this.hl("@keyword.return", syntax.keyword)}
${this.hl("@keyword.debug", syntax.keyword)}
${this.hl("@keyword.exception", syntax.keyword)}
${this.hl("@conditional", syntax.keyword)}
${this.hl("@conditional.ternary", syntax.keyword)}
${this.hl("@repeat", syntax.keyword)}
${this.hl("@debug", syntax.keyword)}
${this.hl("@label", syntax.label)}
${this.hl("@include", syntax.keyword)}
${this.hl("@exception", syntax.keyword)}
${this.hl("@type", syntax.type)}
${this.hl("@type.builtin", syntax.type)}
${this.hl("@type.definition", syntax.type)}
${this.hl("@type.qualifier", syntax.keyword)}
${this.hl("@storageclass", syntax.keyword)}
${this.hl("@namespace", syntax.namespace)}
${this.hl("@module", syntax.namespace)}
${this.hl("@module.builtin", syntax.namespace)}
${this.hl("@property", syntax.property)}
${this.hl("@field", syntax.property)}
${this.hl("@attribute", syntax.attribute)}
${this.hl("@attribute.builtin", syntax.attribute)}
${this.hl("@annotation", syntax.attribute)}
${this.hl("@tag", syntax.tag)}
${this.hl("@tag.attribute", syntax.attribute)}
${this.hl("@tag.builtin", syntax.tag)}
${this.hl("@tag.delimiter", syntax.punctuation)}
${this.hl("@operator", syntax.operator)}
${this.hl("@punctuation", syntax.punctuation)}
${this.hl("@punctuation.delimiter", syntax["punctuation.delimiter"])}
${this.hl("@punctuation.bracket", syntax["punctuation.bracket"])}
${this.hl("@punctuation.special", syntax["punctuation.special"])}
${this.hl("@comment", syntax.comment, { italic: true })}
${this.hl("@comment.documentation", syntax["comment.doc"])}
${this.hl("@comment.error", semantic.error)}
${this.hl("@comment.warning", semantic.warning)}
${this.hl("@comment.todo", semantic.info)}
${this.hl("@comment.note", semantic.info)}
${this.hl("@markup.heading", syntax.title, { bold: true })}
${this.hl("@markup.heading.1", syntax.title, { bold: true })}
${this.hl("@markup.heading.2", syntax.title, { bold: true })}
${this.hl("@markup.italic", syntax.emphasis, { italic: true })}
${this.hl("@markup.strong", syntax["emphasis.strong"], { bold: true })}
${this.hl("@markup.strikethrough", syntax.emphasis)}
${this.hl("@markup.underline", syntax.link_text)}
${this.hl("@markup.link", syntax.link_text)}
${this.hl("@markup.link.url", syntax.link_uri)}
${this.hl("@markup.link.label", syntax.link_text)}
${this.hl("@markup.list", syntax["punctuation.list_marker"])}
${this.hl("@markup.list.checked", semantic.ok)}
${this.hl("@markup.list.unchecked", semantic.error)}
${this.hl("@markup.quote", syntax.comment)}
${this.hl("@markup.raw", syntax["text.literal"])}
${this.hl("@markup.math", syntax.string)}
${this.hl("@diff.plus", semantic.ok)}
${this.hl("@diff.minus", semantic.error)}
${this.hl("@diff.delta", semantic.warning)}

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '${palette.foreground}', bg = '${surfaceBg}' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '${borderCol}', bg = '${surfaceBg}' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '${textMutedCol}', bg = '${tabBarCol}' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '${tabBarCol}' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '${palette.foreground}', bg = '${surfaceBg}', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '${semantic.ok}' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '${semantic.error}' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '${semantic.warning}' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '${semantic.error}' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '${semantic.warning}' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '${semantic.info}' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '${semantic.hint}' })
`;
  }

  private hl(
    group: string,
    fg?: string,
    opts: { bold?: boolean; italic?: boolean } = {},
  ): string {
    if (!fg) return "";
    const attrs: string[] = [];
    attrs.push(`fg = '${fg}'`);
    if (opts.bold) attrs.push("bold = true");
    if (opts.italic) attrs.push("italic = true");
    return `vim.api.nvim_set_hl(0, '${group}', { ${attrs.join(", ")} })`;
  }
}
