import type { Palette } from "../core/types";
import { border, surface } from "../core/ui";
import { PerPaletteGenerator } from "./base";

export class TmuxGenerator extends PerPaletteGenerator {
  name = "tmux";
  description = "tmux terminal multiplexer";
  fileExtension = ".tmuxtheme";

  generate(palette: Palette): string {
    const { ansi, colors: named, semantic } = palette;
    const accent = named.accent_color_2 ?? named.morning_glory ?? ansi.cyan;
    const statusFg = named.grey_chateau ?? ansi.white;
    const borderCol = border(palette);
    const activeBorder = named.accent_color_2 ?? named.ship_cove ?? ansi.blue;
    const surfaceBg = surface(palette);

    return `#!/usr/bin/env bash

# Senzu Theme: ${palette.name}
# Generated by senzu

thm_bg="${palette.background}"
thm_fg="${palette.foreground}"
thm_black="${ansi.black}"
thm_red="${ansi.red}"
thm_green="${ansi.green}"
thm_yellow="${ansi.yellow}"
thm_blue="${ansi.blue}"
thm_magenta="${ansi.magenta}"
thm_cyan="${ansi.cyan}"
thm_white="${ansi.white}"
thm_orange="${named.raw_sienna ?? ansi.red}"
thm_black4="${palette.selection_background}"

# Status line colors
thm_gray="${named.grey ?? "#888888"}"
thm_statusline_bg="${surfaceBg}"
thm_statusline_fg="${statusFg}"
thm_border="${named.grey_three ?? borderCol}"
thm_active_border="${activeBorder}"
thm_highlight="${palette.selection_background}"

# Accent colors
thm_accent="${accent}"
thm_total_black="${palette.appearance === "dark" ? "#000000" : "#ffffff"}"

# Specialized colors
thm_cursor="${palette.cursor}"
thm_visual="${palette.selection_background}"
thm_error="${semantic.error}"
thm_warning="${semantic.warning}"
thm_info="${semantic.info}"
`;
  }
}
