import type { Palette } from "../core/types";
import {
  border,
  elementHover,
  scrollbarThumb,
  surface,
  tabBar,
  textAccent,
  textMuted,
} from "../core/ui";
import { PerPaletteGenerator } from "./base";

/**
 * WezTerm themes in TOML format, the canonical format for the
 * ~/.config/wezterm/colors/ directory.
 */
export class WeztermGenerator extends PerPaletteGenerator {
  name = "wezterm";
  description = "WezTerm terminal emulator (TOML)";
  fileExtension = ".toml";

  generate(palette: Palette): string {
    const { ansi, ansi_bright } = palette;
    const scrollbar = scrollbarThumb(palette);
    const split = border(palette);
    const surfaceBg = surface(palette);
    const tabBarCol = tabBar(palette);
    const textAccentCol = textAccent(palette);
    const textMutedCol = textMuted(palette);
    const elementHoverCol = elementHover(palette);
    const variant = palette.name.toLowerCase().replace(/\s+/g, "-");

    return `# Senzu Theme: ${palette.name}
# Generated by senzu

[metadata]
name = "${variant}"
author = "aliou"
origin_url = ""

[colors]
foreground = '${palette.foreground}'
background = '${palette.background}'

cursor_bg = '${palette.cursor}'
cursor_fg = '${palette.cursor_text}'
cursor_border = '${palette.cursor}'

selection_bg = '${palette.selection_background}'
selection_fg = '${palette.selection_foreground}'

scrollbar_thumb = '${scrollbar}'
split = '${split}'

ansi = [
  '${ansi.black}',
  '${ansi.red}',
  '${ansi.green}',
  '${ansi.yellow}',
  '${ansi.blue}',
  '${ansi.magenta}',
  '${ansi.cyan}',
  '${ansi.white}',
]

brights = [
  '${ansi_bright.black}',
  '${ansi_bright.red}',
  '${ansi_bright.green}',
  '${ansi_bright.yellow}',
  '${ansi_bright.blue}',
  '${ansi_bright.magenta}',
  '${ansi_bright.cyan}',
  '${ansi_bright.white}',
]

[colors.tab_bar]
background = '${tabBarCol}'

[colors.tab_bar.active_tab]
bg_color = '${textAccentCol}'
fg_color = '${palette.background}'

[colors.tab_bar.inactive_tab]
bg_color = '${surfaceBg}'
fg_color = '${textMutedCol}'

[colors.tab_bar.inactive_tab_hover]
bg_color = '${elementHoverCol}'
fg_color = '${palette.foreground}'

[colors.tab_bar.new_tab]
bg_color = '${surfaceBg}'
fg_color = '${textMutedCol}'

[colors.tab_bar.new_tab_hover]
bg_color = '${elementHoverCol}'
fg_color = '${palette.foreground}'
`;
  }
}
