import type { Palette } from "../core/types";
import { PerPaletteGenerator } from "./base";

/** CSS custom-property themes for https://wterm.dev/. */
export class WtermGenerator extends PerPaletteGenerator {
  name = "wterm";
  description = "wterm web terminal";
  fileExtension = ".css";

  generate(palette: Palette): string {
    const { ansi, ansi_bright } = palette;
    const variant = this.paletteKey(palette);

    return `/* Senzu Theme: ${palette.name}
 * Generated by senzu
 *
 * Import this file after the wterm base CSS, then use theme="${variant}".
 */
.wterm.theme-${variant} {
  --term-bg: ${palette.background};
  --term-fg: ${palette.foreground};
  --term-cursor: ${palette.cursor};

  --term-color-0: ${ansi.black};
  --term-color-1: ${ansi.red};
  --term-color-2: ${ansi.green};
  --term-color-3: ${ansi.yellow};
  --term-color-4: ${ansi.blue};
  --term-color-5: ${ansi.magenta};
  --term-color-6: ${ansi.cyan};
  --term-color-7: ${ansi.white};
  --term-color-8: ${ansi_bright.black};
  --term-color-9: ${ansi_bright.red};
  --term-color-10: ${ansi_bright.green};
  --term-color-11: ${ansi_bright.yellow};
  --term-color-12: ${ansi_bright.blue};
  --term-color-13: ${ansi_bright.magenta};
  --term-color-14: ${ansi_bright.cyan};
  --term-color-15: ${ansi_bright.white};
}
`;
  }
}
