import type { Generator, OutputFile, Palette } from "../core/types";
import { border, elevatedSurface, surface, textMuted } from "../core/ui";
import { BatGenerator } from "./bat";

/**
 * Yazi themes are distributed as flavors: one `<name>.yazi` directory per
 * palette containing `flavor.toml` and a matching TextMate theme for syntax
 * highlighted previews.
 */
export class YaziGenerator implements Generator {
  name = "yazi";
  description = "Yazi file manager flavor";

  private readonly tmTheme = new BatGenerator();

  emit(palettes: Palette[]): OutputFile[] {
    return palettes.flatMap((palette) => {
      const variant = palette.name.toLowerCase().replace(/\s+/g, "-");
      const directory = `share/yazi/${variant}.yazi`;

      return [
        {
          relativePath: `${directory}/flavor.toml`,
          contents: this.generate(palette),
        },
        {
          relativePath: `${directory}/tmtheme.xml`,
          contents: this.tmTheme.generate(palette),
        },
      ];
    });
  }

  generate(palette: Palette): string {
    const { ansi, semantic } = palette;
    const bg = palette.background;
    const fg = palette.foreground;
    const panel = surface(palette);
    const elevated = elevatedSurface(palette);
    const muted = textMuted(palette);
    const edge = border(palette);

    return `#:schema https://yazi-rs.github.io/schemas/theme.json
# Senzu flavor: ${palette.name}
# Generated by senzu

[app]
overall = { fg = "${fg}", bg = "${bg}" }

[mgr]
cwd = { fg = "${ansi.cyan}", bold = true }
find_keyword = { fg = "${ansi.yellow}", bold = true, italic = true, underline = true }
find_position = { fg = "${ansi.magenta}", bg = "reset", bold = true, italic = true }
symlink_target = { fg = "${ansi.cyan}", italic = true }
marker_copied = { fg = "${semantic.ok}", bg = "${semantic.ok}" }
marker_cut = { fg = "${semantic.error}", bg = "${semantic.error}" }
marker_marked = { fg = "${semantic.info}", bg = "${semantic.info}" }
marker_selected = { fg = "${ansi.yellow}", bg = "${ansi.yellow}" }
count_copied = { fg = "${bg}", bg = "${semantic.ok}" }
count_cut = { fg = "${bg}", bg = "${semantic.error}" }
count_selected = { fg = "${bg}", bg = "${ansi.yellow}" }
border_style = { fg = "${edge}" }

[tabs]
active = { fg = "${palette.cursor_text}", bg = "${palette.cursor}", bold = true }
inactive = { fg = "${muted}", bg = "${panel}" }

[mode]
normal_main = { fg = "${palette.cursor_text}", bg = "${palette.cursor}", bold = true }
normal_alt = { fg = "${palette.cursor}", bg = "${panel}" }
select_main = { fg = "${bg}", bg = "${ansi.cyan}", bold = true }
select_alt = { fg = "${ansi.cyan}", bg = "${panel}" }
unset_main = { fg = "${bg}", bg = "${semantic.error}", bold = true }
unset_alt = { fg = "${semantic.error}", bg = "${panel}" }

[indicator]
parent = { fg = "${muted}" }
current = { fg = "${palette.cursor}" }
preview = { fg = "${ansi.cyan}" }

[status]
overall = { fg = "${fg}", bg = "${bg}" }
perm_sep = { fg = "${muted}" }
perm_type = { fg = "${ansi.blue}" }
perm_read = { fg = "${ansi.yellow}" }
perm_write = { fg = "${semantic.error}" }
perm_exec = { fg = "${semantic.ok}" }
progress_label = { fg = "${fg}", bold = true }
progress_normal = { fg = "${semantic.ok}", bg = "${panel}" }
progress_error = { fg = "${semantic.warning}", bg = "${semantic.error}" }

[which]
mask = { bg = "${elevated}" }
cand = { fg = "${ansi.cyan}" }
rest = { fg = "${muted}" }
desc = { fg = "${ansi.magenta}" }
separator_style = { fg = "${edge}" }

[confirm]
border = { fg = "${palette.cursor}" }
title = { fg = "${palette.cursor}", bold = true }
body = { fg = "${fg}" }
list = { fg = "${fg}" }
btn_yes = { fg = "${bg}", bg = "${semantic.ok}", bold = true }
btn_no = { fg = "${fg}", bg = "${panel}" }

[spot]
border = { fg = "${palette.cursor}" }
title = { fg = "${palette.cursor}", bold = true }
tbl_col = { fg = "${ansi.cyan}" }
tbl_cell = { fg = "${ansi.yellow}", bg = "${panel}" }

[notify]
title_info = { fg = "${semantic.ok}" }
title_warn = { fg = "${semantic.warning}" }
title_error = { fg = "${semantic.error}" }

[pick]
border = { fg = "${palette.cursor}" }
active = { fg = "${ansi.magenta}", bold = true }
inactive = { fg = "${muted}" }

[input]
border = { fg = "${palette.cursor}" }
title = { fg = "${fg}" }
value = { fg = "${fg}" }
selected = { fg = "${palette.selection_foreground}", bg = "${palette.selection_background}" }

[cmp]
border = { fg = "${palette.cursor}" }
active = { fg = "${palette.selection_foreground}", bg = "${palette.selection_background}" }
inactive = { fg = "${muted}" }

[tasks]
border = { fg = "${palette.cursor}" }
title = { fg = "${fg}" }
hovered = { fg = "${ansi.magenta}", bold = true }

[help]
on = { fg = "${ansi.cyan}" }
run = { fg = "${ansi.magenta}" }
desc = { fg = "${fg}" }
hovered = { fg = "${palette.selection_foreground}", bg = "${palette.selection_background}", bold = true }
footer = { fg = "${bg}", bg = "${fg}" }

[filetype]
rules = [
  { mime = "image/*", fg = "${ansi.cyan}" },
  { mime = "{audio,video}/*", fg = "${ansi.magenta}" },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "${semantic.error}" },
  { mime = "application/{pdf,doc,rtf}", fg = "${ansi.yellow}" },
  { mime = "vfs/{absent,stale}", fg = "${muted}" },
  { url = "*", is = "orphan", bg = "${semantic.error}" },
  { url = "*", is = "exec", fg = "${semantic.ok}" },
  { url = "*/", fg = "${ansi.blue}" },
  { url = "*", fg = "${fg}" },
]
`;
  }
}
