-- Senzu Theme: Senzu Light
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_light'

-- Terminal colors
vim.g.terminal_color_0 = '#f5f5f5'
vim.g.terminal_color_1 = '#ff3333'
vim.g.terminal_color_2 = '#386014'
vim.g.terminal_color_3 = '#876820'
vim.g.terminal_color_4 = '#2952a3'
vim.g.terminal_color_5 = '#6a4abd'
vim.g.terminal_color_6 = '#2B5B77'
vim.g.terminal_color_7 = '#252525'
vim.g.terminal_color_8 = '#787878'
vim.g.terminal_color_9 = '#a02020'
vim.g.terminal_color_10 = '#457039'
vim.g.terminal_color_11 = '#b87520'
vim.g.terminal_color_12 = '#234291'
vim.g.terminal_color_13 = '#5a0069'
vim.g.terminal_color_14 = '#3a596a'
vim.g.terminal_color_15 = '#000000'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#252525', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#252525', bg = '#f5e6d3' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#f5e6d3', bg = '#234291' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#e8d5c0bf' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#e8d5c0bf' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ccc5c4', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#d7af87' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#f5e6d3', bg = '#876820' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#f5e6d3', bg = '#b87520' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#d0ccd1' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#252525', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#605958', bg = '#f5e6d3' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#252525', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#f5e6d3', bg = '#556779' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#787878', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#658349' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#876820' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#b87520' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#252525' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#252525' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#658349' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#252525', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#d0ccd1', bg = '#f5e6d3' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#605958', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#252525', bg = '#f5e6d3', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#386014' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#ff3333' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#a66510' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#ff3333' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#a66510' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#1670af' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#606060' })
