-- Senzu Theme: Senzu Muted Light
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_muted_light'

-- Terminal colors
vim.g.terminal_color_0 = '#fdfdfa'
vim.g.terminal_color_1 = '#b84949'
vim.g.terminal_color_2 = '#6d7f59'
vim.g.terminal_color_3 = '#987b40'
vim.g.terminal_color_4 = '#445987'
vim.g.terminal_color_5 = '#655683'
vim.g.terminal_color_6 = '#3c5971'
vim.g.terminal_color_7 = '#2d2c2a'
vim.g.terminal_color_8 = '#787775'
vim.g.terminal_color_9 = '#913a34'
vim.g.terminal_color_10 = '#4d7134'
vim.g.terminal_color_11 = '#a07542'
vim.g.terminal_color_12 = '#334a84'
vim.g.terminal_color_13 = '#542258'
vim.g.terminal_color_14 = '#3a6f8c'
vim.g.terminal_color_15 = '#0f0e0d'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#2d2c2a', bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#2d2c2a', bg = '#f7f3eb' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#f7f3eb', bg = '#334a84' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#ebe7dfbf' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#ebe7dfbf' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#5c5650' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ccc5c4', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#c9b99a' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#f7f3eb', bg = '#987b40' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#f7f3eb', bg = '#a07542' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#d0cdc6' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#2d2c2a', bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#5c5650', bg = '#f7f3eb' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#2d2c2a', bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#f7f3eb', bg = '#536271' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#787775', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#445987' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#987b40' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#a07542' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#445987' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#6d7f59' })

-- Treesitter highlights
vim.api.nvim_set_hl(0, '@variable', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@variable.parameter.builtin', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@variable.member', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, '@constant.macro', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, '@number', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, '@number.float', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, '@character', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@character.special', { fg = '#655683' })
vim.api.nvim_set_hl(0, '@string', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@string.documentation', { fg = '#c0c0bd' })
vim.api.nvim_set_hl(0, '@string.regexp', { fg = '#a07542' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#c0c0bd' })
vim.api.nvim_set_hl(0, '@string.special', { fg = '#655683' })
vim.api.nvim_set_hl(0, '@string.special.symbol', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@string.special.path', { fg = '#655683' })
vim.api.nvim_set_hl(0, '@string.special.url', { fg = '#655683' })
vim.api.nvim_set_hl(0, '@function', { fg = '#987b40' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, '@function.call', { fg = '#987b40' })
vim.api.nvim_set_hl(0, '@function.macro', { fg = '#987b40' })
vim.api.nvim_set_hl(0, '@method', { fg = '#987b40' })
vim.api.nvim_set_hl(0, '@method.call', { fg = '#987b40' })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.function', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.import', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.type', { fg = '#a07542' })
vim.api.nvim_set_hl(0, '@keyword.modifier', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.repeat', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.return', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.debug', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@keyword.exception', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@conditional', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@conditional.ternary', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@repeat', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@debug', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@label', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@include', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@exception', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@type', { fg = '#a07542' })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#a07542' })
vim.api.nvim_set_hl(0, '@type.definition', { fg = '#a07542' })
vim.api.nvim_set_hl(0, '@type.qualifier', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@storageclass', { fg = '#445987' })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@module', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@module.builtin', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@property', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@field', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@attribute', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@attribute.builtin', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@annotation', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@tag', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@tag.builtin', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@operator', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@punctuation', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@comment', { fg = '#787775', italic = true })
vim.api.nvim_set_hl(0, '@comment.documentation', { fg = '#c0c0bd' })
vim.api.nvim_set_hl(0, '@comment.error', { fg = '#b84949' })
vim.api.nvim_set_hl(0, '@comment.warning', { fg = '#9a7345' })
vim.api.nvim_set_hl(0, '@comment.todo', { fg = '#3a6f8c' })
vim.api.nvim_set_hl(0, '@comment.note', { fg = '#3a6f8c' })
vim.api.nvim_set_hl(0, '@markup.heading', { fg = '#987b40', bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.1', { fg = '#987b40', bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.2', { fg = '#987b40', bold = true })
vim.api.nvim_set_hl(0, '@markup.italic', { fg = '#3c5971', italic = true })
vim.api.nvim_set_hl(0, '@markup.strong', { fg = '#3c5971', bold = true })
vim.api.nvim_set_hl(0, '@markup.strikethrough', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@markup.underline', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@markup.link', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@markup.link.url', { fg = '#655683' })
vim.api.nvim_set_hl(0, '@markup.link.label', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@markup.list', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, '@markup.list.checked', { fg = '#4d7134' })
vim.api.nvim_set_hl(0, '@markup.list.unchecked', { fg = '#b84949' })
vim.api.nvim_set_hl(0, '@markup.quote', { fg = '#787775' })
vim.api.nvim_set_hl(0, '@markup.raw', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, '@markup.math', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, '@diff.plus', { fg = '#4d7134' })
vim.api.nvim_set_hl(0, '@diff.minus', { fg = '#b84949' })
vim.api.nvim_set_hl(0, '@diff.delta', { fg = '#9a7345' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#2d2c2a', bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#d0cdc6', bg = '#f7f3eb' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#5c5650', bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#2d2c2a', bg = '#f7f3eb', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#4d7134' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#b84949' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#9a7345' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#b84949' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#9a7345' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#3a6f8c' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#5f5f5d' })
