-- Senzu Theme: Senzu
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu'

-- Terminal colors
vim.g.terminal_color_0 = '#151515'
vim.g.terminal_color_1 = '#d74545'
vim.g.terminal_color_2 = '#99ad6a'
vim.g.terminal_color_3 = '#fad07a'
vim.g.terminal_color_4 = '#8197bf'
vim.g.terminal_color_5 = '#c6b6ee'
vim.g.terminal_color_6 = '#668799'
vim.g.terminal_color_7 = '#e8e8d3'
vim.g.terminal_color_8 = '#888888'
vim.g.terminal_color_9 = '#902020'
vim.g.terminal_color_10 = '#70b950'
vim.g.terminal_color_11 = '#e6a75a'
vim.g.terminal_color_12 = '#8fbfdc'
vim.g.terminal_color_13 = '#700089'
vim.g.terminal_color_14 = '#8fbfdc'
vim.g.terminal_color_15 = '#f0f0f0'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#e8e8d3', bg = '#151515' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#e8e8d3', bg = '#151515' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#151515', bg = '#b0d0f0' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#1a1a1a' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#1a1a1a' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ccc5c4', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#404040' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#151515', bg = '#fad07a' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#151515', bg = '#e6a75a' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#403c41' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#e8e8d3', bg = '#151515' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#605958', bg = '#151515' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#e8e8d3', bg = '#151515' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#151515', bg = '#556779' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#888888', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#d98870' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#d98870' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#fad07a' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#e6a75a' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#99ad6a' })

-- Treesitter highlights
vim.api.nvim_set_hl(0, '@variable', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@variable.parameter.builtin', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@variable.member', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#d98870' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#d98870' })
vim.api.nvim_set_hl(0, '@constant.macro', { fg = '#d98870' })
vim.api.nvim_set_hl(0, '@number', { fg = '#d98870' })
vim.api.nvim_set_hl(0, '@number.float', { fg = '#d98870' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#d98870' })
vim.api.nvim_set_hl(0, '@character', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@character.special', { fg = '#c6b6ee' })
vim.api.nvim_set_hl(0, '@string', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@string.documentation', { fg = '#c7c7c7' })
vim.api.nvim_set_hl(0, '@string.regexp', { fg = '#e6a75a' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#c7c7c7' })
vim.api.nvim_set_hl(0, '@string.special', { fg = '#c6b6ee' })
vim.api.nvim_set_hl(0, '@string.special.symbol', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@string.special.path', { fg = '#c6b6ee' })
vim.api.nvim_set_hl(0, '@string.special.url', { fg = '#c6b6ee' })
vim.api.nvim_set_hl(0, '@function', { fg = '#fad07a' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#d98870' })
vim.api.nvim_set_hl(0, '@function.call', { fg = '#fad07a' })
vim.api.nvim_set_hl(0, '@function.macro', { fg = '#fad07a' })
vim.api.nvim_set_hl(0, '@method', { fg = '#fad07a' })
vim.api.nvim_set_hl(0, '@method.call', { fg = '#fad07a' })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.function', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.import', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.type', { fg = '#e6a75a' })
vim.api.nvim_set_hl(0, '@keyword.modifier', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.repeat', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.return', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.debug', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@keyword.exception', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@conditional', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@conditional.ternary', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@repeat', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@debug', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@label', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@include', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@exception', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@type', { fg = '#e6a75a' })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#e6a75a' })
vim.api.nvim_set_hl(0, '@type.definition', { fg = '#e6a75a' })
vim.api.nvim_set_hl(0, '@type.qualifier', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@storageclass', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@module', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@module.builtin', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@property', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@field', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@attribute', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@attribute.builtin', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@annotation', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@tag', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@tag.builtin', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@operator', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@punctuation', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@comment', { fg = '#888888', italic = true })
vim.api.nvim_set_hl(0, '@comment.documentation', { fg = '#c7c7c7' })
vim.api.nvim_set_hl(0, '@comment.error', { fg = '#d74545' })
vim.api.nvim_set_hl(0, '@comment.warning', { fg = '#ffaf00' })
vim.api.nvim_set_hl(0, '@comment.todo', { fg = '#5f9ecf' })
vim.api.nvim_set_hl(0, '@comment.note', { fg = '#5f9ecf' })
vim.api.nvim_set_hl(0, '@markup.heading', { fg = '#fad07a', bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.1', { fg = '#fad07a', bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.2', { fg = '#fad07a', bold = true })
vim.api.nvim_set_hl(0, '@markup.italic', { fg = '#8fbfdc', italic = true })
vim.api.nvim_set_hl(0, '@markup.strong', { fg = '#8fbfdc', bold = true })
vim.api.nvim_set_hl(0, '@markup.strikethrough', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@markup.underline', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@markup.link', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@markup.link.url', { fg = '#c6b6ee' })
vim.api.nvim_set_hl(0, '@markup.link.label', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@markup.list', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, '@markup.list.checked', { fg = '#afd787' })
vim.api.nvim_set_hl(0, '@markup.list.unchecked', { fg = '#d74545' })
vim.api.nvim_set_hl(0, '@markup.quote', { fg = '#888888' })
vim.api.nvim_set_hl(0, '@markup.raw', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, '@markup.math', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, '@diff.plus', { fg = '#afd787' })
vim.api.nvim_set_hl(0, '@diff.minus', { fg = '#d74545' })
vim.api.nvim_set_hl(0, '@diff.delta', { fg = '#ffaf00' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#e8e8d3', bg = '#151515' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#403c41', bg = '#151515' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#605958', bg = '#151515' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#151515' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#e8e8d3', bg = '#151515', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#afd787' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#d74545' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#ffaf00' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#d74545' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#ffaf00' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#5f9ecf' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#a08070' })
