-- Senzu Theme: Senzu Mono Light
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_mono_light'

-- Terminal colors
vim.g.terminal_color_0 = '#f5f5f5'
vim.g.terminal_color_1 = '#cc0000'
vim.g.terminal_color_2 = '#7d7163'
vim.g.terminal_color_3 = '#6a6564'
vim.g.terminal_color_4 = '#4a5e81'
vim.g.terminal_color_5 = '#555555'
vim.g.terminal_color_6 = '#576270'
vim.g.terminal_color_7 = '#252525'
vim.g.terminal_color_8 = '#787878'
vim.g.terminal_color_9 = '#ffe5ea'
vim.g.terminal_color_10 = '#3d6c25'
vim.g.terminal_color_11 = '#707070'
vim.g.terminal_color_12 = '#4a5e81'
vim.g.terminal_color_13 = '#909090'
vim.g.terminal_color_14 = '#645c54'
vim.g.terminal_color_15 = '#000000'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#252525', bg = '#f5f0e8' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#252525', bg = '#f5f0e8' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#f5f0e8', bg = '#4a5e81' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#e8e0d5bf' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#e8e0d5bf' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#6a6564', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#d8c8b8' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#f5f0e8', bg = '#6a6564' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#f5f0e8', bg = '#707070' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#d0ccd1' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#252525', bg = '#f5f0e8' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#605958', bg = '#f5f0e8' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#252525', bg = '#f5f0e8' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#f5f0e8', bg = '#576270' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#909090', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#796858' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#7d7163' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#7d7163' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#787878' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#4a5e81' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#7d7163' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#4a5e81' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#252525' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#787878' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#252525' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#4a5e81' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#796858' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#252525', bg = '#f5f0e8' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#d0ccd1', bg = '#f5f0e8' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#605958', bg = '#f5f0e8' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#f5f0e8' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#252525', bg = '#f5f0e8', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#3d6c25' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#cc0000' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#a36000' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#cc0000' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#a36000' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#0060a3' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#796858' })
