-- Senzu Theme: Senzu HC
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_hc'

-- Terminal colors
vim.g.terminal_color_0 = '#060606'
vim.g.terminal_color_1 = '#ff5050'
vim.g.terminal_color_2 = '#c0d880'
vim.g.terminal_color_3 = '#ffe080'
vim.g.terminal_color_4 = '#98b0e0'
vim.g.terminal_color_5 = '#d8c8ff'
vim.g.terminal_color_6 = '#78a0b8'
vim.g.terminal_color_7 = '#f8f8f0'
vim.g.terminal_color_8 = '#909090'
vim.g.terminal_color_9 = '#b02020'
vim.g.terminal_color_10 = '#8cd468'
vim.g.terminal_color_11 = '#ffc060'
vim.g.terminal_color_12 = '#aad4f8'
vim.g.terminal_color_13 = '#8800a8'
vim.g.terminal_color_14 = '#aad4f8'
vim.g.terminal_color_15 = '#f8f8f8'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#f8f8f0', bg = '#060606' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#f8f8f0', bg = '#060606' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#060606', bg = '#c0e0ff' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#0e0e0ebf' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#0e0e0ebf' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#e0d8d0', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#303030' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#060606', bg = '#ffe080' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#060606', bg = '#ffc060' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#282828' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#f8f8f0', bg = '#060606' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#605958', bg = '#060606' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#f8f8f0', bg = '#060606' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#060606', bg = '#556779' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#909090', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#ffe080' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#ffc060' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#c0d880' })

-- Treesitter highlights
vim.api.nvim_set_hl(0, '@variable', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@variable.parameter.builtin', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@variable.member', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, '@constant.macro', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, '@number', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, '@number.float', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, '@character', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@character.special', { fg = '#d8c8ff' })
vim.api.nvim_set_hl(0, '@string', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@string.documentation', { fg = '#d8d8d8' })
vim.api.nvim_set_hl(0, '@string.regexp', { fg = '#ffc060' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#d8d8d8' })
vim.api.nvim_set_hl(0, '@string.special', { fg = '#d8c8ff' })
vim.api.nvim_set_hl(0, '@string.special.symbol', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@string.special.path', { fg = '#d8c8ff' })
vim.api.nvim_set_hl(0, '@string.special.url', { fg = '#d8c8ff' })
vim.api.nvim_set_hl(0, '@function', { fg = '#ffe080' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, '@function.call', { fg = '#ffe080' })
vim.api.nvim_set_hl(0, '@function.macro', { fg = '#ffe080' })
vim.api.nvim_set_hl(0, '@method', { fg = '#ffe080' })
vim.api.nvim_set_hl(0, '@method.call', { fg = '#ffe080' })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.function', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.import', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.type', { fg = '#ffc060' })
vim.api.nvim_set_hl(0, '@keyword.modifier', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.repeat', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.return', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.debug', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@keyword.exception', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@conditional', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@conditional.ternary', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@repeat', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@debug', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@label', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@include', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@exception', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@type', { fg = '#ffc060' })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#ffc060' })
vim.api.nvim_set_hl(0, '@type.definition', { fg = '#ffc060' })
vim.api.nvim_set_hl(0, '@type.qualifier', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@storageclass', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@module', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@module.builtin', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@property', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@field', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@attribute', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@attribute.builtin', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@annotation', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@tag', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@tag.builtin', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@operator', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@punctuation', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@comment', { fg = '#909090', italic = true })
vim.api.nvim_set_hl(0, '@comment.documentation', { fg = '#d8d8d8' })
vim.api.nvim_set_hl(0, '@comment.error', { fg = '#ff5050' })
vim.api.nvim_set_hl(0, '@comment.warning', { fg = '#ffc800' })
vim.api.nvim_set_hl(0, '@comment.todo', { fg = '#60b8ff' })
vim.api.nvim_set_hl(0, '@comment.note', { fg = '#60b8ff' })
vim.api.nvim_set_hl(0, '@markup.heading', { fg = '#ffe080', bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.1', { fg = '#ffe080', bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.2', { fg = '#ffe080', bold = true })
vim.api.nvim_set_hl(0, '@markup.italic', { fg = '#aad4f8', italic = true })
vim.api.nvim_set_hl(0, '@markup.strong', { fg = '#aad4f8', bold = true })
vim.api.nvim_set_hl(0, '@markup.strikethrough', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@markup.underline', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@markup.link', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@markup.link.url', { fg = '#d8c8ff' })
vim.api.nvim_set_hl(0, '@markup.link.label', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@markup.list', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, '@markup.list.checked', { fg = '#c0f060' })
vim.api.nvim_set_hl(0, '@markup.list.unchecked', { fg = '#ff5050' })
vim.api.nvim_set_hl(0, '@markup.quote', { fg = '#909090' })
vim.api.nvim_set_hl(0, '@markup.raw', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, '@markup.math', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, '@diff.plus', { fg = '#c0f060' })
vim.api.nvim_set_hl(0, '@diff.minus', { fg = '#ff5050' })
vim.api.nvim_set_hl(0, '@diff.delta', { fg = '#ffc800' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#f8f8f0', bg = '#060606' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#282828', bg = '#060606' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#605958', bg = '#060606' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#060606' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#f8f8f0', bg = '#060606', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#c0f060' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#ff5050' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#ffc800' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#ff5050' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#ffc800' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#60b8ff' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#c09070' })
