-- Senzu Theme: Senzu Light
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_light'

-- Terminal colors
vim.g.terminal_color_0 = '#f5f5f5'
vim.g.terminal_color_1 = '#ff3333'
vim.g.terminal_color_2 = '#386014'
vim.g.terminal_color_3 = '#876820'
vim.g.terminal_color_4 = '#2952a3'
vim.g.terminal_color_5 = '#6a4abd'
vim.g.terminal_color_6 = '#2B5B77'
vim.g.terminal_color_7 = '#252525'
vim.g.terminal_color_8 = '#787878'
vim.g.terminal_color_9 = '#a02020'
vim.g.terminal_color_10 = '#457039'
vim.g.terminal_color_11 = '#b87520'
vim.g.terminal_color_12 = '#234291'
vim.g.terminal_color_13 = '#5a0069'
vim.g.terminal_color_14 = '#3a596a'
vim.g.terminal_color_15 = '#000000'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#252525', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#252525', bg = '#f5e6d3' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#f5e6d3', bg = '#234291' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#ebd9c5' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#ebd9c5' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ccc5c4', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#d7af87' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#f5e6d3', bg = '#876820' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#f5e6d3', bg = '#b87520' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#d0ccd1' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#252525', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#605958', bg = '#f5e6d3' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#252525', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#f5e6d3', bg = '#556779' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#787878', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#658349' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#876820' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#b87520' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#252525' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#252525' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#658349' })

-- Treesitter highlights
vim.api.nvim_set_hl(0, '@variable', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@variable.parameter.builtin', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@variable.member', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, '@constant.macro', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, '@number', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, '@number.float', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, '@character', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@character.special', { fg = '#6a4abd' })
vim.api.nvim_set_hl(0, '@string', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@string.documentation', { fg = '#c7c7c7' })
vim.api.nvim_set_hl(0, '@string.regexp', { fg = '#b87520' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#c7c7c7' })
vim.api.nvim_set_hl(0, '@string.special', { fg = '#6a4abd' })
vim.api.nvim_set_hl(0, '@string.special.symbol', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@string.special.path', { fg = '#6a4abd' })
vim.api.nvim_set_hl(0, '@string.special.url', { fg = '#6a4abd' })
vim.api.nvim_set_hl(0, '@function', { fg = '#876820' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#954d3b' })
vim.api.nvim_set_hl(0, '@function.call', { fg = '#876820' })
vim.api.nvim_set_hl(0, '@function.macro', { fg = '#876820' })
vim.api.nvim_set_hl(0, '@method', { fg = '#876820' })
vim.api.nvim_set_hl(0, '@method.call', { fg = '#876820' })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.function', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.import', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.type', { fg = '#b87520' })
vim.api.nvim_set_hl(0, '@keyword.modifier', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.repeat', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.return', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.debug', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@keyword.exception', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@conditional', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@conditional.ternary', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@repeat', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@debug', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@label', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@include', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@exception', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@type', { fg = '#b87520' })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#b87520' })
vim.api.nvim_set_hl(0, '@type.definition', { fg = '#b87520' })
vim.api.nvim_set_hl(0, '@type.qualifier', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@storageclass', { fg = '#2952a3' })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@module', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@module.builtin', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@property', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@field', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@attribute', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@attribute.builtin', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@annotation', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@tag', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@tag.builtin', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@operator', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@punctuation', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@comment', { fg = '#787878', italic = true })
vim.api.nvim_set_hl(0, '@comment.documentation', { fg = '#c7c7c7' })
vim.api.nvim_set_hl(0, '@comment.error', { fg = '#ff3333' })
vim.api.nvim_set_hl(0, '@comment.warning', { fg = '#a66510' })
vim.api.nvim_set_hl(0, '@comment.todo', { fg = '#1670af' })
vim.api.nvim_set_hl(0, '@comment.note', { fg = '#1670af' })
vim.api.nvim_set_hl(0, '@markup.heading', { fg = '#876820', bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.1', { fg = '#876820', bold = true })
vim.api.nvim_set_hl(0, '@markup.heading.2', { fg = '#876820', bold = true })
vim.api.nvim_set_hl(0, '@markup.italic', { fg = '#2B5B77', italic = true })
vim.api.nvim_set_hl(0, '@markup.strong', { fg = '#2B5B77', bold = true })
vim.api.nvim_set_hl(0, '@markup.strikethrough', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@markup.underline', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@markup.link', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@markup.link.url', { fg = '#6a4abd' })
vim.api.nvim_set_hl(0, '@markup.link.label', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@markup.list', { fg = '#252525' })
vim.api.nvim_set_hl(0, '@markup.list.checked', { fg = '#386014' })
vim.api.nvim_set_hl(0, '@markup.list.unchecked', { fg = '#ff3333' })
vim.api.nvim_set_hl(0, '@markup.quote', { fg = '#787878' })
vim.api.nvim_set_hl(0, '@markup.raw', { fg = '#2B5B77' })
vim.api.nvim_set_hl(0, '@markup.math', { fg = '#658349' })
vim.api.nvim_set_hl(0, '@diff.plus', { fg = '#386014' })
vim.api.nvim_set_hl(0, '@diff.minus', { fg = '#ff3333' })
vim.api.nvim_set_hl(0, '@diff.delta', { fg = '#a66510' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#252525', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#d0ccd1', bg = '#f5e6d3' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#605958', bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#f5e6d3' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#252525', bg = '#f5e6d3', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#386014' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#ff3333' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#a66510' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#ff3333' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#a66510' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#1670af' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#606060' })
