-- Senzu Theme: Senzu HC
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_hc'

-- Terminal colors
vim.g.terminal_color_0 = '#060606'
vim.g.terminal_color_1 = '#ff5050'
vim.g.terminal_color_2 = '#c0d880'
vim.g.terminal_color_3 = '#ffe080'
vim.g.terminal_color_4 = '#98b0e0'
vim.g.terminal_color_5 = '#d8c8ff'
vim.g.terminal_color_6 = '#78a0b8'
vim.g.terminal_color_7 = '#f8f8f0'
vim.g.terminal_color_8 = '#909090'
vim.g.terminal_color_9 = '#b02020'
vim.g.terminal_color_10 = '#8cd468'
vim.g.terminal_color_11 = '#ffc060'
vim.g.terminal_color_12 = '#aad4f8'
vim.g.terminal_color_13 = '#8800a8'
vim.g.terminal_color_14 = '#aad4f8'
vim.g.terminal_color_15 = '#f8f8f8'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#f8f8f0', bg = '#060606' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#f8f8f0', bg = '#060606' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#060606', bg = '#c0e0ff' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#1c1c1c' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ccc5c4', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#303030' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#060606', bg = '#ffe080' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#060606', bg = '#ffc060' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#282828' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#f8f8f0', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#888888', bg = '#1c1c1c' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#f8f8f0', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#060606', bg = '#78a0b8' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#909090', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#c0d880' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#f0a080' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#ffe080' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#ffc060' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#98b0e0' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#f8f8f0' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#aad4f8' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#c0d880' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#f8f8f0', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#282828', bg = '#1c1c1c' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#888888', bg = '#060606' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#060606' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#f8f8f0', bg = '#1c1c1c', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#c0f060' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#ff5050' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#ffc800' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#ff5050' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#ffc800' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#60b8ff' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#c09070' })
