-- Senzu Theme: Senzu Warm
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_warm'

-- Terminal colors
vim.g.terminal_color_0 = '#1c1510'
vim.g.terminal_color_1 = '#d74545'
vim.g.terminal_color_2 = '#99ad6a'
vim.g.terminal_color_3 = '#fad07a'
vim.g.terminal_color_4 = '#8197bf'
vim.g.terminal_color_5 = '#c6b6ee'
vim.g.terminal_color_6 = '#668799'
vim.g.terminal_color_7 = '#edd9b8'
vim.g.terminal_color_8 = '#8a8070'
vim.g.terminal_color_9 = '#902020'
vim.g.terminal_color_10 = '#70b950'
vim.g.terminal_color_11 = '#e6a75a'
vim.g.terminal_color_12 = '#8fbfdc'
vim.g.terminal_color_13 = '#700089'
vim.g.terminal_color_14 = '#8fbfdc'
vim.g.terminal_color_15 = '#f0e4d0'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#edd9b8', bg = '#1c1510' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#edd9b8', bg = '#1c1510' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#1c1510', bg = '#c8b878' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#1c1c1c' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ccc5c4', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#4a3828' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#1c1510', bg = '#fad07a' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#1c1510', bg = '#e6a75a' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#3c2c1c' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#edd9b8', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#888888', bg = '#1c1c1c' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#edd9b8', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#1c1510', bg = '#668799' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#8a8070', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#99ad6a' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#d98870' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#d98870' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#fad07a' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#e6a75a' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#edd9b8' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#8197bf' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#edd9b8' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#8fbfdc' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#99ad6a' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#edd9b8', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#3c2c1c', bg = '#1c1c1c' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#888888', bg = '#1c1510' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#1c1510' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#edd9b8', bg = '#1c1c1c', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#afd787' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#d74545' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#ffaf00' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#d74545' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#ffaf00' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#5f9ecf' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#a08070' })
