-- Senzu Theme: Senzu Mono
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_mono'

-- Terminal colors
vim.g.terminal_color_0 = '#151515'
vim.g.terminal_color_1 = '#c95c5c'
vim.g.terminal_color_2 = '#b39066'
vim.g.terminal_color_3 = '#ccc5c4'
vim.g.terminal_color_4 = '#7a8aa6'
vim.g.terminal_color_5 = '#c7c7c7'
vim.g.terminal_color_6 = '#556779'
vim.g.terminal_color_7 = '#e8e8d3'
vim.g.terminal_color_8 = '#888888'
vim.g.terminal_color_9 = '#40000a'
vim.g.terminal_color_10 = '#afd787'
vim.g.terminal_color_11 = '#888888'
vim.g.terminal_color_12 = '#7a8aa6'
vim.g.terminal_color_13 = '#606060'
vim.g.terminal_color_14 = '#a0a8b0'
vim.g.terminal_color_15 = '#f0f0f0'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#e8e8d3', bg = '#151515' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#e8e8d3', bg = '#151515' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#151515', bg = '#7a8aa6' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#1c1c1cbf' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#1c1c1cbf' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ccc5c4', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#404040' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#151515', bg = '#ccc5c4' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#151515', bg = '#888888' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#403c41' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#e8e8d3', bg = '#151515' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#605958', bg = '#151515' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#e8e8d3', bg = '#151515' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#151515', bg = '#556779' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#606060', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#a08070' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#b39066' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#b39066' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#888888' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#7a8aa6' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#b39066' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#7a8aa6' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#888888' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#e8e8d3' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#7a8aa6' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#a08070' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#e8e8d3', bg = '#151515' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#403c41', bg = '#151515' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#605958', bg = '#151515' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#151515' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#e8e8d3', bg = '#151515', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#afd787' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#c95c5c' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#ffaf00' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#c95c5c' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#ffaf00' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#7a8aa6' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#a08070' })
