-- Senzu Theme: Senzu Muted Light
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_muted_light'

-- Terminal colors
vim.g.terminal_color_0 = '#fdfdfa'
vim.g.terminal_color_1 = '#b84949'
vim.g.terminal_color_2 = '#6d7f59'
vim.g.terminal_color_3 = '#987b40'
vim.g.terminal_color_4 = '#445987'
vim.g.terminal_color_5 = '#655683'
vim.g.terminal_color_6 = '#3c5971'
vim.g.terminal_color_7 = '#2d2c2a'
vim.g.terminal_color_8 = '#787775'
vim.g.terminal_color_9 = '#913a34'
vim.g.terminal_color_10 = '#4d7134'
vim.g.terminal_color_11 = '#a07542'
vim.g.terminal_color_12 = '#334a84'
vim.g.terminal_color_13 = '#542258'
vim.g.terminal_color_14 = '#3a6f8c'
vim.g.terminal_color_15 = '#0f0e0d'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#2d2c2a', bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#2d2c2a', bg = '#f7f3eb' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#f7f3eb', bg = '#334a84' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#1c1c1c' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ccc5c4', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#c9b99a' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#f7f3eb', bg = '#987b40' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#f7f3eb', bg = '#a07542' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#d0cdc6' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#2d2c2a', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#888888', bg = '#1c1c1c' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#2d2c2a', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#f7f3eb', bg = '#3c5971' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#787775', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#6d7f59' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#8c594a' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#445987' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#987b40' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#a07542' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#445987' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#2d2c2a' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#3c5971' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#6d7f59' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#2d2c2a', bg = '#1c1c1c' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#d0cdc6', bg = '#1c1c1c' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#888888', bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#f7f3eb' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#2d2c2a', bg = '#1c1c1c', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#4d7134' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#b84949' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#9a7345' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#b84949' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#9a7345' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#3a6f8c' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#5f5f5d' })
