-- Senzu Theme: Senzu HC Light
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_hc_light'

-- Terminal colors
vim.g.terminal_color_0 = '#f5f5f5'
vim.g.terminal_color_1 = '#c00000'
vim.g.terminal_color_2 = '#507020'
vim.g.terminal_color_3 = '#7a5000'
vim.g.terminal_color_4 = '#1a3a80'
vim.g.terminal_color_5 = '#4a2090'
vim.g.terminal_color_6 = '#306070'
vim.g.terminal_color_7 = '#000000'
vim.g.terminal_color_8 = '#707070'
vim.g.terminal_color_9 = '#8a1010'
vim.g.terminal_color_10 = '#1f5d10'
vim.g.terminal_color_11 = '#8a5000'
vim.g.terminal_color_12 = '#0a4a7a'
vim.g.terminal_color_13 = '#600080'
vim.g.terminal_color_14 = '#0a4a7a'
vim.g.terminal_color_15 = '#505050'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#000000', bg = '#fafafa' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#000000', bg = '#fafafa' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#fafafa', bg = '#0a3a8a' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#f0f0f0bf' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#f0f0f0bf' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#605958' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#404040', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#e8d0c0' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#fafafa', bg = '#7a5000' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#fafafa', bg = '#8a5000' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#e0e0e0' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#000000', bg = '#fafafa' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#605958', bg = '#fafafa' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#000000', bg = '#fafafa' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#fafafa', bg = '#4a6070' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#707070', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#507020' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#8a3a10' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#8a3a10' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#1a3a80' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#7a5000' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#8a5000' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#0a4a7a' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#000000' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#1a3a80' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#000000' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#0a4a7a' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#507020' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#000000', bg = '#fafafa' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#e0e0e0', bg = '#fafafa' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#605958', bg = '#fafafa' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#fafafa' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#000000', bg = '#fafafa', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#1f5d10' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#c00000' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#8a4a00' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#c00000' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#8a4a00' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#0a4a8a' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#8a3a10' })
