-- Senzu Theme: Senzu Muted
-- Generated by senzu

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.g.colors_name = 'senzu_muted'

-- Terminal colors
vim.g.terminal_color_0 = '#101010'
vim.g.terminal_color_1 = '#cc4d4d'
vim.g.terminal_color_2 = '#909c6e'
vim.g.terminal_color_3 = '#e8c88c'
vim.g.terminal_color_4 = '#7a8aa6'
vim.g.terminal_color_5 = '#b8aed3'
vim.g.terminal_color_6 = '#617b87'
vim.g.terminal_color_7 = '#dad6c8'
vim.g.terminal_color_8 = '#7a7a7a'
vim.g.terminal_color_9 = '#7e2e23'
vim.g.terminal_color_10 = '#98b67c'
vim.g.terminal_color_11 = '#d8a16c'
vim.g.terminal_color_12 = '#83adc3'
vim.g.terminal_color_13 = '#5c1e68'
vim.g.terminal_color_14 = '#7db7cc'
vim.g.terminal_color_15 = '#f9f5ec'

-- Base highlights
vim.api.nvim_set_hl(0, 'Normal', { fg = '#dad6c8', bg = '#101010' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = '#dad6c8', bg = '#101010' })

-- Cursor
vim.api.nvim_set_hl(0, 'Cursor', { fg = '#101010', bg = '#a6c3d9' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#1e1e1cbf' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#1e1e1cbf' })

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#58534f' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#c2bdb8', bold = true })

-- Selection
vim.api.nvim_set_hl(0, 'Visual', { bg = '#3c3b38' })

-- Search
vim.api.nvim_set_hl(0, 'Search', { fg = '#101010', bg = '#e8c88c' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#101010', bg = '#d8a16c' })

-- Splits and UI
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#3c3936' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#dad6c8', bg = '#101010' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#58534f', bg = '#101010' })

-- Popup menu
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#dad6c8', bg = '#101010' })
vim.api.nvim_set_hl(0, 'PmenuSel', { fg = '#101010', bg = '#4f5c69' })

-- Syntax highlighting
vim.api.nvim_set_hl(0, 'Comment', { fg = '#7a7a7a', italic = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#909c6e' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#c88a77' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#c88a77' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#7a8aa6' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#e8c88c' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#d8a16c' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#83adc3' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#dad6c8' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#7a8aa6' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#dad6c8' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#83adc3' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#909c6e' })

-- Floating windows
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = '#dad6c8', bg = '#101010' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#3c3936', bg = '#101010' })

-- Tabline
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#58534f', bg = '#101010' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#101010' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#dad6c8', bg = '#101010', bold = true })

-- Diff
vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#98b67c' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#cc4d4d' })
vim.api.nvim_set_hl(0, 'DiffChange', { fg = '#d9a45a' })

-- Diagnostics
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#cc4d4d' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#d9a45a' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#7db7cc' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#c0a48c' })
