#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Mono Light
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-mono-light.sh ] && . ~/.config/fzf/senzu-mono-light.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#252525,bg:#f5f0e8,hl:#6a6564,fg+:#252525,bg+:#d8c8b8,hl+:#6a6564,info:#0060a3,border:#d0ccd1,prompt:#4a5e81,pointer:#4a5e81,marker:#7d7163,spinner:#555555,header:#605958,gutter:#d8c8b8,preview-fg:#252525,preview-bg:#f5f0e8"
