#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Warm
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-warm.sh ] && . ~/.config/fzf/senzu-warm.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#edd9b8,bg:#1c1510,hl:#fad07a,fg+:#edd9b8,bg+:#4a3828,hl+:#fad07a,info:#5f9ecf,border:#3c2c1c,prompt:#8197bf,pointer:#c8b878,marker:#99ad6a,spinner:#c6b6ee,header:#6a5a50,gutter:#4a3828,preview-fg:#edd9b8,preview-bg:#1c1510"
