#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Warm Light
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-warm-light.sh ] && . ~/.config/fzf/senzu-warm-light.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#2b241d,bg:#fbead6,hl:#876820,fg+:#2b241d,bg+:#d8b992,hl+:#876820,info:#8a5a2a,border:#d6c6b6,prompt:#2952a3,pointer:#7a4f20,marker:#386014,spinner:#6a4abd,header:#68584a,gutter:#d8b992,preview-fg:#2b241d,preview-bg:#fbead6"
