#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu.sh ] && . ~/.config/fzf/senzu.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#e8e8d3,bg:#151515,hl:#fad07a,fg+:#e8e8d3,bg+:#404040,hl+:#fad07a,info:#5f9ecf,border:#403c41,prompt:#8197bf,pointer:#b0d0f0,marker:#99ad6a,spinner:#c6b6ee,header:#605958,gutter:#404040,preview-fg:#e8e8d3,preview-bg:#151515"
