#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Muted
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-muted.sh ] && . ~/.config/fzf/senzu-muted.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#dad6c8,bg:#101010,hl:#e8c88c,fg+:#dad6c8,bg+:#3c3b38,hl+:#e8c88c,info:#7db7cc,border:#3c3936,prompt:#7a8aa6,pointer:#a6c3d9,marker:#909c6e,spinner:#b8aed3,header:#58534f,gutter:#3c3b38,preview-fg:#dad6c8,preview-bg:#101010"
