#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu HC
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-hc.sh ] && . ~/.config/fzf/senzu-hc.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#f8f8f0,bg:#060606,hl:#ffe080,fg+:#f8f8f0,bg+:#303030,hl+:#ffe080,info:#60b8ff,border:#282828,prompt:#98b0e0,pointer:#c0e0ff,marker:#c0d880,spinner:#d8c8ff,header:#605958,gutter:#303030,preview-fg:#f8f8f0,preview-bg:#060606"
