#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Cold Light
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-cold-light.sh ] && . ~/.config/fzf/senzu-cold-light.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#1f2a34,bg:#edf6ff,hl:#876820,fg+:#1f2a34,bg+:#b8d0e6,hl+:#876820,info:#2a6f9c,border:#cad6e0,prompt:#2952a3,pointer:#234291,marker:#386014,spinner:#6a4abd,header:#556575,gutter:#b8d0e6,preview-fg:#1f2a34,preview-bg:#edf6ff"
