#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Muted Light
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-muted-light.sh ] && . ~/.config/fzf/senzu-muted-light.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#2d2c2a,bg:#f7f3eb,hl:#987b40,fg+:#2d2c2a,bg+:#c9b99a,hl+:#987b40,info:#3a6f8c,border:#d0cdc6,prompt:#445987,pointer:#334a84,marker:#6d7f59,spinner:#655683,header:#5c5650,gutter:#c9b99a,preview-fg:#2d2c2a,preview-bg:#f7f3eb"
