#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu HC Light
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-hc-light.sh ] && . ~/.config/fzf/senzu-hc-light.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#000000,bg:#fafafa,hl:#7a5000,fg+:#000000,bg+:#e8d0c0,hl+:#7a5000,info:#0a4a8a,border:#e0e0e0,prompt:#1a3a80,pointer:#0a3a8a,marker:#507020,spinner:#4a2090,header:#605958,gutter:#e8d0c0,preview-fg:#000000,preview-bg:#fafafa"
