#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Mono
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-mono.sh ] && . ~/.config/fzf/senzu-mono.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#e8e8d3,bg:#151515,hl:#ccc5c4,fg+:#e8e8d3,bg+:#404040,hl+:#ccc5c4,info:#7a8aa6,border:#403c41,prompt:#7a8aa6,pointer:#7a8aa6,marker:#b39066,spinner:#c7c7c7,header:#605958,gutter:#404040,preview-fg:#e8e8d3,preview-bg:#151515"
