#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Light
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-light.sh ] && . ~/.config/fzf/senzu-light.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#252525,bg:#f5e6d3,hl:#876820,fg+:#252525,bg+:#d7af87,hl+:#876820,info:#1670af,border:#d0ccd1,prompt:#2952a3,pointer:#234291,marker:#386014,spinner:#6a4abd,header:#605958,gutter:#d7af87,preview-fg:#252525,preview-bg:#f5e6d3"
