#!/usr/bin/env sh
# Senzu Theme for fzf: Senzu Cold
# Generated by senzu
#
# Source this file in your shell rc to apply (zsh/bash):
#
#   [ -f ~/.config/fzf/senzu-cold.sh ] && . ~/.config/fzf/senzu-cold.sh
#
# It appends the Senzu --color spec to FZF_DEFAULT_OPTS, preserving any other
# fzf options you set. To switch variants, source a different senzu fzf file
# instead (fzf merges --color flags, last one wins per element).

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }--color=fg:#b8d4ed,bg:#10161c,hl:#fad07a,fg+:#b8d4ed,bg+:#283a4a,hl+:#fad07a,info:#5f9ecf,border:#1c2d3c,prompt:#8197bf,pointer:#b0d0f0,marker:#99ad6a,spinner:#c6b6ee,header:#505e6a,gutter:#283a4a,preview-fg:#b8d4ed,preview-bg:#10161c"
