import type { Palette } from "../core/types";
import { PerPaletteGenerator } from "./base";

export class GhosttyGenerator extends PerPaletteGenerator {
  name = "ghostty";
  description = "Ghostty terminal emulator";
  fileExtension = "";

  generate(palette: Palette): string {
    const { ansi, ansi_bright } = palette;

    return `# Senzu Theme: ${palette.name}
# Generated by senzu

background = ${palette.background}
foreground = ${palette.foreground}

cursor-color = ${palette.cursor}
cursor-text = ${palette.cursor_text}

selection-background = ${palette.selection_background}
selection-foreground = ${palette.selection_foreground}

palette = 0=${ansi.black}
palette = 1=${ansi.red}
palette = 2=${ansi.green}
palette = 3=${ansi.yellow}
palette = 4=${ansi.blue}
palette = 5=${ansi.magenta}
palette = 6=${ansi.cyan}
palette = 7=${ansi.white}

palette = 8=${ansi_bright.black}
palette = 9=${ansi_bright.red}
palette = 10=${ansi_bright.green}
palette = 11=${ansi_bright.yellow}
palette = 12=${ansi_bright.blue}
palette = 13=${ansi_bright.magenta}
palette = 14=${ansi_bright.cyan}
palette = 15=${ansi_bright.white}
`;
  }
}
